language: node_js
node_js:
  - '10'
cache: npm
install:
  - cd truffle
  - npm install
  - cd -
jobs:
  include:
    - stage: Test(contract)
      name: Linter
      before_script: cd truffle
      script: npx eslint .
      after_script: cd -
    - stage: Test(contract)
      name: Unit tests
      before_script: cd truffle
      script: ./test.sh
      after_script: cd -
    - stage: Test(contract)
      name: Unit tests with coverage report
      before_script: cd truffle
      script: CONTINUOUS_INTEGRATION=true SOLIDITY_COVERAGE=true ./test.sh
      after_script: cd -
notifications:
  slack:
    rooms:
      - secure: KPLIVAG6QEHLBufLm5jpTFwrUKcrjmZwKF4HpgqiAp1uOnBu8C0V2rBlAP/ZJrfIHqS5QM28VKNeq6+iueeDyoc3RdUYYTwe7AmoU1ghNCTrQJ6gsPLQOuvxEP4DQg+AjVB4sARlM+qWEG4wIlaxxVuiYrc+OaljBLgeDxto0GFfBO67f4OZBTK3sbNuJb4xGYoxo9o0LkYwaM+9ngYKfH/8S9ozfunAGuh6HPiZup7bYEDKbkitehRpGb3aIuY6fRF/sU3EUOcqMn55HlILXjnXbQwvKLnh4c1AcnnEx7NWnDpnJPJv1rKQs3ALf+q1mpdA9WqJYznE3dL/W5VXv6FjCeaARpU2WWJ+dH0lldg/d5BvuJLk+QRxsHXAe7jgRmJJ7+rY87j7hA9gayYw3abTCG+r6+KE57ywb1WnlMnhp5+AF6HNYQuRk7k433QtvzIj8Ekek9BErt3jKblcyEDWUC+t2nGf8Avvu32AOfqK4Pw2UeE6CmDfS20JzVzEtgd7ODK7t1G5T2y6bYXeP5Qocil13zlflgcszs1/9ce757ToW/2qZeBkKuMdvPDxTRu0dTKyOxz98CkPo8IxgfEuNrGv9tSoAYb8swnSQ7W+NSRqvWdJ5stkas70HFtC0imnSj/xqTkO5H5B+8KERNPzpkesRn8IA/ZgWlyG91w=
    on_success: change
    on_failure: always
